### ISSUE TITLE
When revoking modules an error occured

### ISSUE THREAD

**Issue by sjoerdvandijkt4e** [Tools4everBV/HelloID-Conn-Prov-Target-Ysis#10]
When revoking the modules, the script returns sub-permissions and the script runs in an error. from line 190 we need to check the type of action. When revoking the sub-permissions must not be returned I guess.

    $outputContext.SubPermissions.Add([PSCustomObject]@{
        DisplayName = $permission.Value
        Reference   = [PSCustomObject]@{
            Id = $permission.Name
        }
    })

must be changed to:

    if ($actionContext.Operation -ne "revoke"){
    $outputContext.SubPermissions.Add([PSCustomObject]@{
        DisplayName = $permission.Value
        Reference   = [PSCustomObject]@{
            Id = $permission.Name
        }
    })}

Can someone check this?

**Comment by Rick-Jongbloed** [comment]
solved in PR
