### ISSUE TITLE
Complex mapping - AD is currently a GUID

### ISSUE THREAD

**Issue by rscholtelubberink** [Tools4everBV/HelloID-Conn-Prov-Target-Ysis#6]
Is now: Person.Accounts._bccd667xxxxxa9d4acfc64c19a3d6.mail
Should be: Person.Accounts.MicrosoftActiveDirectory.mail

I will fix this during GitHub duty this week

**Comment by rhouthuijzen** [comment]
Fixed in new branch. Linked to new branch

**Comment by Rick-Jongbloed** [comment]
Solved in https://github.com/Tools4everBV/HelloID-Conn-Prov-Target-Ysis/pull/17
