### ISSUE TITLE
Conditional event configuration should be documented.

### ISSUE THREAD

**Issue by Rick-Jongbloed** [Tools4everBV/HelloID-Conn-Prov-Target-Ysis#7]
Readme should be expanded. Is currently:

Conditional Event
A conditional event needs to be set up based on changes of the discipline. On this event a notification can be configured to send an e-mail to the Ysis-administrator.

Should list the steps to take to create the conditional event

**Comment by rhouthuijzen** [comment]
linked to new branch. Fixed in new readme

**Comment by Rick-Jongbloed** [comment]
Solved in https://github.com/Tools4everBV/HelloID-Conn-Prov-Target-Ysis/pull/17
